### ISSUE TITLE
Default backend uses military time for show start/end times

### ISSUE THREAD

**Issue by ianmobbs** [ianmobbs/KVRX-Website#19]
Pretty sure this is just something you can specify either in your model or your admin prefs

**Comment by jmhern** [comment]
Just pushed a change. If the format needs seconds it's just a matter of appending ':%S' to TIME INPUT FORMATS
https://github.com/ianmobbs/KVRX-Website/commit/a837f42a8cc6943599b2f4f390e6dbfb0517ffd8

**Comment by ianmobbs** [comment]
Great!

Still having some issues though. For example 6am and 6pm are both "06:00"

**Comment by jmhern** [comment]
Added am/pm!
https://github.com/ianmobbs/KVRX-Website/commit/5cba4d035e39eec197d45710f19622802cba292b
