### ISSUE TITLE
Playlist isn't showing all songs or repeat songs on show detail page

### ISSUE THREAD

**Issue by ianmobbs** [ianmobbs/KVRX-Website#20]
Recently discovered. Needs investigating

**Comment by jmhern** [comment]
Alright so I just found out why this happens. Whenever you make a playlist and you go to the song list the most recent edited song will be highlighted. Then you'll click save to save the changes. Whatever song(s) was/were highlighted before you saved will display on the show detail page. Pretty interesting issue.

**Comment by jmhern** [comment]
Also because the option `blank=True` is enabled you can also make the page not show anything by not having anything highlighted.

**Comment by ianmobbs** [comment]
Totally interesting. I guess the workflow makes sense (1. Make playlist, 2. Add Song object (inherently un-selected), 3. Save (with song object unselected)). We need to keep `blank=True` active though because people have playlists without songs and add them as they go pretty frequently. I'm gonna say this is closed for now since that's something we'll address in our DJ portal

**Comment by jmhern** [comment]
Does `all()` return all the members in the field regardless if they're highlighted?
