### ISSUE TITLE
Users can create pages with same link as pre-defined pages (e.g. 'shows')

### ISSUE THREAD

**Issue by ianmobbs** [ianmobbs/KVRX-Website#21]
Will probably have to hardcode a list of custom KVRX pages (`/shows`, `/about`, whatever) and keep users from creating things in that list?

**Comment by mattjegan** [comment]
I submitted a PR for this [here](https://github.com/ianmobbs/KVRX-Website/pull/23)

**Comment by ianmobbs** [comment]
@mattjegan Thank you! This solved our issue.
